name: saku_tani_mobile
description: "SakuTani adalah aplikasi manajemen keuangan digital yang dirancang khusus untuk membantu petani dalam mencatat pemasukan dan pengeluaran hasil pertanian secara praktis, real-time, dan mudah digunakan."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  font_awesome_flutter: ^10.8.0
  http: ^1.4.0
  intl: ^0.20.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
